#PATHS

RAW_DATA_DIR : 'data/raw/'
PROC_DATA_DIR : 'data/processed/'
INTERIM_DATA_DIR : 'data/interim/'
VALID_ACTIONS : {
  'breakout': [3,4]
}
MODEL_SAVE_DIR : 'models_/'
VIS_PREDS_DIR : 'data/vis/'
CMP_FMT : '.tar.bz2'
OVERWRITE_INTERIM_GAZE : False
